-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 21:09:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ler13c
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ler13c` ;

-- -----------------------------------------------------
-- Schema ler13c
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ler13c` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `ler13c` ;

-- -----------------------------------------------------
-- Table `ler13c`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`petstore` (
  `pst_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(45) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT UNSIGNED NOT NULL,
  `pst_phone` BIGINT UNSIGNED ZEROFILL NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) UNSIGNED NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ler13c`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`customer` (
  `cus_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(30) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(45) NOT NULL,
  `cus_city` VARCHAR(45) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT UNSIGNED NOT NULL,
  `cus_phone` BIGINT UNSIGNED ZEROFILL NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ler13c`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ler13c`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ler13c`.`pet` (
  `pet_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_id` TINYINT UNSIGNED NULL,
  `pst_id` TINYINT UNSIGNED NOT NULL,
  `pet_name` VARCHAR(30) NOT NULL,
  `pet_type` VARCHAR(30) NOT NULL,
  `pet_sex` ENUM('f','m') NOT NULL,
  `pet_cost` DECIMAL(7,2) UNSIGNED NOT NULL,
  `pet_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `pet_age` TINYINT UNSIGNED NOT NULL,
  `pet_color` VARCHAR(25) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y','n') NOT NULL,
  `pet_neuter` ENUM('y','n') NOT NULL,
  `pet_notes` VARCHAR(45) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC),
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC),
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `ler13c`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `ler13c`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ler13c`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Gerwin\'s Turtle Store', '123 Main Street', 'Tallahassee', 'FL', 11111, 15551111111, 'gerwins@gerwins.com', 'gerwins.com', 200020.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Place', '321 Side Street', 'Tallahassee', 'FL', 22222, 15552222222, 'pet@place.com', 'petplace.com', 909090.09, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Font Pets', '1337 Comic Way', 'Gainesville', 'GA', 33333, 15553333333, 'font@fontpets.com', 'fotpents.com', 444445.98, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Cat Corner', '7331 Sans Lane', 'Orlando', 'FL', 44444, 15554444444, 'catc@catcorner.com', 'catcorner.com', 103947.22, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Kitty Junction', '224 Papyrus Street', 'Orlando', 'FL', 55555, 15555555555, 'kitty@kittyjunction.com', 'kittyjunction.com', 100000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Palace', '222 Over Avenue', 'Tampa', 'FL', 77777, 15557777777, 'pet@petpalace.com', 'petpalace.com', 200000.00, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets for IT Majors', '345 Learning Way', 'Miami', 'FL', 88888, 15558888888, 'it@petsforit.com', 'petsforit.com', 333333.33, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets for English Majors', '567 Call Street', 'Miami', 'FL', 99999, 15559999999, 'eng@petsforeng.com', 'petsforeng.com', 454545.54, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Dog House', '222 Dog Avenue', 'Tallahassee', 'FL', 10101, 15551112222, 'dog@house.com', 'doghouse.com', 987654.32, NULL);
INSERT INTO `ler13c`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'PetStore', '123 Generic Way', 'Pensacola', 'FL', 12121, 15551113333, 'pet@store.com', 'petstore.com', 123456.78, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ler13c`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Olivia', 'Mosby', '123 Clarinet Street', 'Columbus', 'OH', 99998, 15551234567, 'olivia@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'John', 'Roger', '321 Trombone Street', 'Jacksonville', 'FL', 99997, 15552345678, 'john@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Carl', 'Edwards', '567 Bunny Street', 'Tampa', 'FL', 88887, 15553456789, 'carl@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Charlie', 'Newton', '234 Guitar Street', 'Orlando', 'FL', 77776, 15554567890, 'charlie@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Ashley', 'Chang', '123 Percussion Avenue', 'Tallahassee', 'FL', 77775, 15555678901, 'ashley@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Eric', 'Earl', '987 Viola Lane', 'Minneapolis', 'MN', 55557, 15556789012, 'eric@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Dalton', 'Green', '678 Conductor Road', 'Detroit', 'MI', 44443, 15557890123, 'dalton@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Anabel', 'Brown', '123 Piccolo Drive', 'New York', 'NY', 55554, 15558901234, 'anabel@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Tom', 'Doe', '543 Nothing Avenue', 'Columbus', 'OH', 33332, 15559012345, 'tom@gmail.com', NULL);
INSERT INTO `ler13c`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_notes`) VALUES (DEFAULT, 'Leah', 'Smith', '123 Marimba Court', 'Tallahassee', 'FL', 22221, 15550123456, 'leah@gmail.com', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ler13c`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `ler13c`;
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 10, 'doggo', 'dog', 'm', 1500.00, 2000.00, 12, 'white', '2015-09-20', 'y', 'n', '10');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 9, 'amalgamate', 'dog', 'f', 2500.00, 3000.00, 16, 'white', '2015-09-15', 'y', 'y', '9');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 8, 'temmie', 'dog', 'f', 2000.00, 2500.00, 2, 'white', '2015-01-12', 'y', 'n', '8');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 7, 'gyftrot', 'deer', 'm', 6500.00, 7000.00, 4, 'brown', '2014-02-13', 'y', 'y', '7');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 6, 'aaron', 'horse', 'm', 4250.00, 4500.00, 12, 'white', '2015-09-15', 'y', 'n', '6');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 5, 'froggit', 'frog', 'm', 200.00, 250.00, 1, 'green', '2013-08-14', 'n', 'y', '5');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, 4, 'vegetoid', 'fish', 'm', 40.00, 45.00, 1, 'orange', '2013-08-14', 'n', 'n', '4');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 3, 'snowdrake', 'bird', 'f', 2000.00, 2500.00, 3, 'white', '2012-02-14', 'y', 'n', '3');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 2, 'whimsum', 'butterfly', 'f', 75.00, 100.00, 2, 'yellow', '2016-02-14', 'n', 'y', '2');
INSERT INTO `ler13c`.`pet` (`pet_id`, `cus_id`, `pst_id`, `pet_name`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 1, 'shyren', 'fish', 'f', 25.00, 150.00, 1, 'blue', '2016-01-02', 'y', 'y', '1');

COMMIT;

use ler13c;

show tables;

select * from pet;
select * from customer;
select * from petstore;